### ISSUE TITLE
Can you give me a trained model for test?

### ISSUE THREAD

**Issue by xfguo-ucas** [ShinyCode/image-outpainting#1]
Hi, I'm interested in this project. It looks great. Can you give a model for test my data?
Thanks!

**Comment by ShinyCode** [comment]
Hi!

Thanks for taking the time to look at our project. We won't be releasing the models at this time, but we've put together a much more detailed README to hopefully give you and others some pointers on how to use our code and train your own image outpainting model.

Hope this helps!
