### ISSUE TITLE
Why does the middle part of the reconstructed image look bad?

### ISSUE THREAD

**Issue by BigRiceBall-zz** [ShinyCode/image-outpainting#2]
Hi,

I am not so sure why the middle part of the reconstructed image looks bad. Based on your poster and some example images in your GitHub, the middle part of the reconstructed image looks exactly the same as the original image.
However, I trained a model based on your instructions, the middle part of the reconstructed image looks bad. In addition, your training animation also shows some final results whose middle part is also bad.

I think that you only select the two sides from the reconstructed image and select the middle part from the input image to create an image. 

Is it right?

**Comment by ShinyCode** [comment]
Hi!

Thanks for your comment! Yes, that's exactly right and expected!

When training, the MSE loss is only applied to the sides of the generator output (the "unmasked" parts), so there is no penalty for deviating from the ground truth for the center part of the image (this is as done in the Iizuka paper). The final reconstructed image indeed takes the cropped image (which corresponds to the center of the ground truth), and overlays it on top of the generator output (again, similar to what is done in the Iizuka paper).

Feel free to look at the loss equations in our report/poster to see how the masking is exactly done. Hope this clears things up, and don't hesitate to re-open if you have any more questions!
