### ISSUE TITLE
Help: MemoryError

### ISSUE THREAD

**Issue by hshsilver** [ShinyCode/image-outpainting#3]
Hello, I try to run your codes on my computer according to the steps in the "README.md". However, there exists a problem called "**MemoryError**". 
Before the step to run "run.sh", I have added my virtual memory to fix this problem. Now my computer is of 16GB (physical memory) +around 30GB (virtual memory). Unfortunately, when I run the "run.sh", "MemoryError" come out again and again.
Have you met this kind of problem? Is there something wrong with my operations?

PS: In the README.md, a line says:"**idx_train = list(set(range(36500)) - set(test_indices))**"
I cannot find **test_indices**, and change it to **idx_test**instead.
Is that operation correct?

Thanks for your reply!

Silver
2019-04-15

**Comment by hshsilver** [comment]
By the way, my lab environment is Ubuntu16 with 1080Ti

**Comment by ShinyCode** [comment]
Hi Silver,

Thanks for stopping by to check out the repo! As you have seen, the code was a bit rough (was for a class project) and a bit old, but I can try to help.

Regarding `test_indices`, you are absolutely right - it should be `idx_test`. We're basically just filtering out the test indices so we don't have overlap between the two sets.

Regarding the `MemoryError`, I don't remember encountering this issue before. Somewhat of a generic debugging strategy, but could you run `nvidia-smi` and post the output here? That would help with diagnosing the source of the problem.

Hope this helps!

**Comment by ShinyCode** [comment]
Will close this for now. Feel free to re-open if you still have the issue!
