### ISSUE TITLE
recursive_paint

### ISSUE THREAD

**Issue by XiaoYangon** [ShinyCode/image-outpainting#4]
At the end of the paper, iterative paint proposed  iterative paint. Is it to synthesize an image from the left and right of the image as the input ?

**Comment by ShinyCode** [comment]
Hi! I just saw your issue right now - sorry about that. The idea behind iteratively applying the outpainting process is as follows:

Applying outpainting once extends the image on the left and the right by say, N pixels. If we now outpaint the outpainted image, we have extended the original image on the left and the right by 2N pixels. So, we can arbitrarily extend the original image to as long as we want, with the caveat that the noise will compound as we go further away from the original image.

Hope that helps!
